#!/bin/sh
# postrm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

[ -L /opt/hws/config ] && rm /opt/hws/config
[ -L /opt/hws/security ] && rm /opt/hws/security
[ -L /opt/hws/otel ] && rm /opt/hws/otel
[ -L /opt/hws/site ] && rm /opt/hws/site
[ -L /opt/hws/logs ] && rm /opt/hws/logs
[ -L /opt/hws/LICENSE ] && rm /opt/hws/LICENSE

exit 0