#!/bin/bash
testCredentials () {
    output=`/opt/Navisphere/bin/naviseccli -User $username -Password $password -Address $address -Scope $scope getagent`
    if [ $? -eq 0 ]; then
        serviceprocessor=$address
        echo -e 'scope\t' $scope > ~/MS_HW_navispherecli
        echo -e 'address\t' $address >> ~/MS_HW_navispherecli
    else
        erroroutput+=" username=$username \n scope=$scope \n address=$address \n $output \n\n"
    fi
    }


#Main
echo MS_HW_NAS_INVENTORY_START
/nas/bin/nas_inventory -info -all
echo MS_HW_NAS_INVENTORY_END

username=$1
password=$2

if [[ $username =~ "USERNAME" ]]; then
    echo MS_HW_NAS_Not_Compatible
    exit
fi

# See if we've already run the tests and know the answer
scope=`grep -i scope ~/MS_HW_navispherecli | cut -f 2`
address=`grep -i address ~/MS_HW_navispherecli | cut -f 2`
if [ -z "$scope" ]; then
    testCredentials
fi

# Run tests to find a working service processor address
if [ -z "$serviceprocessor" ]; then
    # SPA Host File, Scope 0 (Global)
    address=`grep -i SPA /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=0
    testCredentials
fi
if [ -z "$serviceprocessor" ]; then
    # SPA Host File, Scope 1 (Global)
    address=`grep -i SPA /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=1
    testCredentials
fi
if [ -z "$serviceprocessor" ]; then
    # SPA Host File, Scope 2 (LDAP)
    address=`grep -i SPA /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=2
    testCredentials
fi
if [ -z "$serviceprocessor" ]; then
    # SPB Host File, Scope 0 (Global)
    address=`grep -i SPB /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=0
    testCredentials
fi
if [ -z "$serviceprocessor" ]; then
    # SPB Host File, Scope 1 (Global)
    address=`grep -i SPB /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=1
    testCredentials
fi
if [ -z "$serviceprocessor" ]; then
    # SPB Host File, Scope 2 (LDAP)
    address=`grep -i SPB /etc/hosts | cut -f 1 -d " "| cut -f 1`
    scope=2
    testCredentials
fi

# If we have good credentials, run the commands
if [ -n "$serviceprocessor" ]; then
    /opt/Navisphere/bin/naviseccli -User $username -Password $password -Address $serviceprocessor -Scope $scope getall
    /opt/Navisphere/bin/naviseccli -User $username -Password $password -Address $serviceprocessor -Scope $scope storagepool -list
    if [ -f ~/MS_HW_NaviSphereCLI_Failure3 ]; then
    echo MS_HW_NAS_NaviSphereCLI_OK
    rm -f ~/MS_HW_NaviSphereCLI_Failure3
    fi
    if [ -f ~/MS_HW_NaviSphereCLI_Failure2 ]; then
    echo MS_HW_NAS_NaviSphereCLI_OK
    mv ~/MS_HW_NaviSphereCLI_Failure2 ~/MS_HW_NaviSphereCLI_Failure3
    fi
    if [ -f ~/MS_HW_NaviSphereCLI_Failure ]; then
    echo MS_HW_NAS_NaviSphereCLI_OK
    mv ~/MS_HW_NaviSphereCLI_Failure ~/MS_HW_NaviSphereCLI_Failure2
    fi
else
# Echo error output
    echo -e $erroroutput
    echo -e $erroroutput > ~/MS_HW_NaviSphereCLI_Failure
# If we get excessive failed authentication attempts, then we want the collect to fail with a timeout to avoid lots of missings
    if [[ $erroroutput =~ "excessive failed authentication attempts" ]] ; then
        echo MS_HW_NAS_Authentication_blocked
    elif [[ $erroroutput =~ "Authentication failed" ]] ; then
        echo MS_HW_NAS_Authentication_failed
    elif grep -i SP[AB] /etc/hosts; then
        echo MS_HW_NAS_No_SP_In_Hosts
    else
        echo MS_HW_NAS_NaviSphereCLI_Failure
    fi

fi