#!/bin/sh
for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
do
    /usr/sbin/lscfg -vp -l $DISK|/bin/tr "." " "|/usr/bin/awk -v diskId=$DISK 'BEGIN {
        manufacturer = "";
        fruNumber = "";
        serialNumber = "";
    }
    /.*/ {
        if ($1 == "Manufacturer")
        {
            manufacturer = $2;
        }

        if ($1 == "FRU" && $2 == "Number")
        {
            fruNumber = $3;
        }

        if ($1 == "Serial" && $2 == "Number")
        {
            serialNumber = $3;
        }
    }
    END {
        print "MSHW;" diskId ";" manufacturer ";" serialNumber " (FRU: " fruNumber ")"
    }'
done