#!/bin/sh
LANG=C
export LANG

ERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=/dev/r$1 of=/dev/null count=20 2>&1`
if /usr/bin/test "$?" = "0" ; then
    STATUS="OK;Working"
else
    STATUS=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '{
            if ($3 ~ /ermission/)
            {
                print "UNKNOWN;Insufficient privileges"
            }
            else if ($3 ~ /o such file/)
            {
                print "UNKNOWN;" $3
            }
            else
            {
                print "ALARM;" $3
            }
        }'`
fi
TODAY=`/usr/bin/date +%m%d0000%y`
ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
if /usr/bin/test $ERRORCOUNT -gt 0 ; then
    LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
fi
/usr/bin/echo "MSHW;$STATUS;$ERRORCOUNT;$LASTERROR"
exit

