#!/bin/sh
LANG=C
export LANG
TODAY=`/usr/bin/date +%m%d0000%y`
ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
if /usr/bin/test $ERRORCOUNT -gt 0 ; then
    LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
fi
/usr/bin/echo "MSHW;$ERRORCOUNT;$LASTERROR"
exit