#!/bin/sh
# postrm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -d /opt/metricshub ]; then
  if [ -L /opt/metricshub/config ]; then
     rm -f /opt/metricshub/config
  fi

  if [ -L /opt/metricshub/security ]; then
     rm -f /opt/metricshub/security
  fi

  if [ -L /opt/metricshub/otel ]; then
     rm -f /opt/metricshub/otel
  fi

  if [ -L /opt/metricshub/site ]; then
    rm -f /opt/metricshub/site
  fi

  if [ -L /opt/metricshub/logs ]; then
    rm -f /opt/metricshub/logs
  fi

  if [ -L /opt/metricshub/LICENSE ]; then
    rm -f /opt/metricshub/LICENSE
  fi

  if [ -L /opt/metricshub/connectors ]; then
    rm -f /opt/metricshub/connectors
  fi
fi

exit 0