#!/bin/sh
if [ -f /etc/lsattr ]
    then LSATTR=/etc/lsattr
    else LSATTR=/usr/sbin/lsattr
fi
for NIC in `%{SUDO:/usr/sbin/netstat -D}/usr/sbin/netstat -D |awk '/ent_dd/ {print $1} ' |cut -b 7-9`
do
    echo MS_HW_entstat_Start: $NIC
    /usr/bin/entstat -d en$NIC
    echo MS_HW_entstat_End: $NIC
done