#!/bin/sh
SMARTD=$1
SMARTCTL=$2
TMPFILE=/tmp/MS_HW_smartmontoolsHDF_$$

$SMARTD -c>$TMPFILE
$SMARTD -q onecheck>>$TMPFILE

DISKIDLIST=`cat $TMPFILE|awk '/^Device: .* is SMART capable/ {
    deviceID = $2;
    if (substr(deviceID, length(deviceID), 1) == ",")
    {
        deviceID = substr(deviceID, 1, length(deviceID)-1);
    }
    print deviceID
}'`

/bin/rm -f $TMPFILE

for DISKID in $DISKIDLIST
do
    $SMARTCTL -a $DISKID|awk -v deviceID=$DISKID 'BEGIN {
        foundTemperature = 0;
        warningThreshold = "";
    }
    {
        if ($0 ~ /^Current Drive Temperature: *[0-9]* C$/)
        {
            foundTemperature = 1;
        }

        if ($1 == "194" && $10 ~ /[0-9]+/)
        {
          foundTemperature = 1;
          warningThreshold = 53;
        }

        if ($0 ~ /^Drive Trip Temperature: /)
        {
            warningThreshold = $4;
        }
    }
    END {
        if (foundTemperature == 1)
        {
            print "MSHW;" deviceID ";" warningThreshold
        }
    }'
done